services:
  my-project:
    build:
      dockerfile: ./Dockerfile
      target: deployment
    env_file:
      - path: env/prod.env
        required: true
    restart: always

    # Add your volume mounts here
    # volumes:
    #   - ./credentials:/app/credentials
    #   - ./data:/app/data
